### ISSUE TITLE
@Deprecated

### ISSUE THREAD

**Issue by XIAYM-gh** [1689295608/MiraiBot#8]
-

**Comment by XIAYM-gh** [comment]
或者也可以使用 RandomAccessFile
使用seek方法把指针移动到文件末尾然后输出内容
也很高效

**Comment by XIAYM-gh** [comment]
顺便催一下ManagerX 
出了记得踢我一下（

**Comment by NekoWs** [comment]
> 

预期寒假期间开发完毕

**Comment by NekoWs** [comment]
> 在你的LogUtil.java中 我发现你的日志追加方法是先把日志内容读出来再合并新内容，这样不够高效，并且日志内容一旦变大就容易爆IO
> 
> 建议使用java.nio.file.Files.write() (它有追加写模式
> 
> XD

的确如此，感谢建议

**Comment by NekoWs** [comment]
已根据建议修改（[52e9442d090e94d647432bd39f6e83b0331ff062](https://github.com/1689295608/MiraiBot/commit/52e9442d090e94d647432bd39f6e83b0331ff062)）
